services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres/flicker:/var/lib/postgresql/data  # Project-specific folder
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${MF_PGPASSWORD:-look_to_the_stars}
      - POSTGRES_USER=${MF_PGUSER:-flicker}
      - POSTGRES_DB=flicker